-- MySQL Script generated by MySQL Workbench
-- Fri Apr 23 17:39:54 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_generation_game_online
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_generation_game_online
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_generation_game_online` DEFAULT CHARACTER SET utf8 ;
USE `db_generation_game_online` ;

-- -----------------------------------------------------
-- Table `db_generation_game_online`.`tb_classe`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_generation_game_online`.`tb_classe` ;

CREATE TABLE IF NOT EXISTS `db_generation_game_online`.`tb_classe` (
  `idtb_classe` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `arma` VARCHAR(45) NOT NULL,
  `munição` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idtb_classe`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_generation_game_online`.`tb_personagem`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_generation_game_online`.`tb_personagem` ;

CREATE TABLE IF NOT EXISTS `db_generation_game_online`.`tb_personagem` (
  `idtb_personagem` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(20) NOT NULL,
  `força` INT NOT NULL,
  `defesa` INT NOT NULL,
  `vida` INT NOT NULL,
  `velocidade` INT NOT NULL,
  `classe_id` INT NOT NULL,
  PRIMARY KEY (`idtb_personagem`),
  INDEX `fk_tb_personagem_tb_classe_idx` (`classe_id` ASC) VISIBLE,
  CONSTRAINT `fk_tb_personagem_tb_classe`
    FOREIGN KEY (`classe_id`)
    REFERENCES `db_generation_game_online`.`tb_classe` (`idtb_classe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO `db_generation_game_online`.`tb_classe` (`nome`, `arma`, `munição`) VALUES ('fuzil assalto', 'M4A1', 'balas de fogo');
INSERT INTO `db_generation_game_online`.`tb_classe` (`nome`, `arma`, `munição`) VALUES ('fuzil de precissão', 'M82', 'balas congelantes');
INSERT INTO `db_generation_game_online`.`tb_classe` (`nome`, `arma`, `munição`) VALUES ('smts', 'MP5', 'balas explossivas');
INSERT INTO `db_generation_game_online`.`tb_classe` (`nome`, `arma`, `munição`) VALUES ('pistola', 'Sykov', 'balas de raios');
INSERT INTO `db_generation_game_online`.`tb_classe` (`nome`, `arma`, `munição`) VALUES ('explosivos', 'pila', 'destruição em massa');

INSERT INTO `db_generation_game_online`.`tb_personagem` ( `nome`, `força`, `defesa`, `vida`, `velocidade`, `classe_id`) VALUES ('cavaleiro das trevas', '5000', '3500', '3000', '900', '1');
INSERT INTO `db_generation_game_online`.`tb_personagem` (`nome`, `força`, `defesa`, `vida`, `velocidade`, `classe_id`) VALUES ('bobo da corte', '3000', '6000', '2500', '1300', '3');
INSERT INTO `db_generation_game_online`.`tb_personagem` (`nome`, `força`, `defesa`, `vida`, `velocidade`, `classe_id`) VALUES ('plebleu', '1500', '2800', '7000', '1600', '2');
INSERT INTO `db_generation_game_online`.`tb_personagem` (`nome`, `força`, `defesa`, `vida`, `velocidade`, `classe_id`) VALUES ('Rei', '6000', '3000', '3000', '700', '4');
INSERT INTO `db_generation_game_online`.`tb_personagem` (`nome`, `força`, `defesa`, `vida`, `velocidade`, `classe_id`) VALUES ('meretriz', '4000', '2500', '4000', '1000', '5');
INSERT INTO `db_generation_game_online`.`tb_personagem` (`nome`, `força`, `defesa`, `vida`, `velocidade`, `classe_id`) VALUES ('Bispo', '4500', '3800', '3200', '950', '1');
INSERT INTO `db_generation_game_online`.`tb_personagem` (`nome`, `força`, `defesa`, `vida`, `velocidade`, `classe_id`) VALUES ('Rainha', '5000', '3200', '4000', '1000', '4');
INSERT INTO `db_generation_game_online`.`tb_personagem` (`nome`, `força`, `defesa`, `vida`, `velocidade`, `classe_id`) VALUES ('alaude', '3700', '4200', '5000', '1200', '3');

select * from tb_personagem;
select * from tb_personagem where força > 2000;
select * from tb_personagem where defesa>= 1000 and defesa<=2000;
select * from tb_personagem where nome like "%c%";
select tb_personagem.nome, tb_personagem.força, tb_personagem.defesa, tb_personagem.vida, tb_personagem.velocidade,tb_classe.nome, tb_classe.arma, tb_classe.munição from tb_personagem inner join tb_classe on tb_personagem.classe_id= tb_classe.idtb_classe;
select tb_personagem.nome, tb_personagem.força, tb_personagem.defesa, tb_personagem.vida, tb_personagem.velocidade,tb_classe.nome, tb_classe.arma, tb_classe.munição from tb_personagem inner join tb_classe on tb_personagem.classe_id= tb_classe.idtb_classe where tb_classe.nome="pistola";